name: 构建并发布Docker镜像

on:
  push:
    branches: [ "main", "master" ]
    # 当版本标签被推送时触发
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main", "master" ]

env:
  # ghcr.io的镜像仓库名称
  REGISTRY: ghcr.io
  # github.repository 是 owner/repo 格式的自动变量
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # 用于为GITHUB_TOKEN写入ID令牌
      id-token: write

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      # 设置Docker Buildx
      - name: 设置Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 登录到GitHub容器注册表
      - name: 登录到容器注册表
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 提取元数据（标签、标签）
      - name: 提取Docker元数据
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          # 设置标签规则
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,format=long

      # 构建并推送Docker镜像
      - name: 构建和推送Docker镜像
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # 错误中提到的缓存问题，使用GitHub Actions缓存替代
          cache-from: type=gha
          cache-to: type=gha,mode=max