name: Docker Image CI

on:
  push:
    branches: [ "main", "master", "stable" ] # 根据您的分支策略调整
  pull_request:
    branches: [ "main", "master", "stable" ] # 根据您的分支策略调整

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2



    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository | lower }}:latest
          ghcr.io/${{ github.repository | lower }}:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: Image digest
      run: echo "Image pushed to GHCR with digest ${{ steps.build-push.outputs.digest }}"